name: keep-render-awake
on:
  schedule:
    - cron: "*/5 * * * *"   # запуск каждые 5 минут (UTC)
  workflow_dispatch:        # возможность запустить вручную
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health
        run: curl -fsS "$PING_URL" || true
        env:
          PING_URL: ${{ secrets.PING_URL }}
